-module(iaTS).
-export([master/1]).

master(FEN) ->

  linda_kernel:start(),

  TreeTS = linda_kernel:create_ts(),

  %% position when generated by explorator
  %% {Father_fen, Move, Rank, Fen}
  %% {string, string, integer, string}

  %% position after evaluation
  %% {Father_fen, Move, Rank, Fen, Eval}
  %% {string, string, integer, string, float}

  %% position after extended
  %% {Father_fen, Move, Rank, Fen, Eval, Ext}
  %% {string, string, integer, string, float, boolean}


  linda_kernel:out(TreeTS, {"", "no move", 0, FEN}),
  {Father_fen, Move, Rank, Fen} = linda_kernel:in(TreeTS, {string, string, integer, string}),

  linda_kernel:out(TreeTS, {Father_fen, Move, Rank, Fen, 0.0}),
  {Father_fen, Move, Rank, Fen, Eval} = linda_kernel:in(TreeTS, {string, string, integer, string, float}),

  linda_kernel:out(TreeTS, {Father_fen, Move, Rank, Fen, Eval, true}),
  {Father_fen, Move, Rank, Fen, Eval, Ext} = linda_kernel:in(TreeTS, {string, string, integer, string, float, boolean}),

  io:format("{~p, ~p, ~p, ~p, ~p, ~p}~n", [Father_fen, Move, Rank, Fen, Eval, Ext]).